name: readaper
description: "A reading app for managing and organizing your books and reading lists."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ^3.35.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  get: ^4.7.2
  dio: ^5.4.3
  path: ^1.9.0
  pie_menu: ^3.3.0
  sqflite: ^2.3.3+1
  get_storage: ^2.1.1
  share_plus: ^10.0.2
  extended_image: ^8.2.1
  cupertino_icons: ^1.0.8
  haptic_feedback: ^0.5.1+1
  markdown_widget: ^2.3.2+8
  easy_localization: ^3.0.3
  flex_color_scheme: ^7.3.1
  flutter_easyloading: ^3.0.5
  receive_sharing_intent: ^1.8.1
  loading_animation_widget: ^1.3.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: NotoSerifSC
      fonts:
        - asset: assets/fonts/NotoSerifSC-Regular.otf
